name: BigTech AI Monitor

on:
  schedule:
    - cron: "0 9 */5 * *"
  workflow_dispatch:

jobs:
  run-bot:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run BigTech Bot
        run: python main_bigtech_ai.py
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK2 }}
